using Finbuckle.MultiTenant.AspNetCore.Extensions;
using Idmt.Plugin.Configuration;
using Idmt.Plugin.Features;
using Idmt.Plugin.Features.Admin;
using Idmt.Plugin.Middleware;
using Idmt.Plugin.Models;
using Idmt.Plugin.Persistence;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace Idmt.Plugin.Extensions;

public delegate Task SeedDataAsync(IServiceProvider services);

/// <summary>
/// Extension methods for configuring IDMT application pipeline
/// </summary>
public static class ApplicationBuilderExtensions
{
    /// <summary>
    /// Adds IDMT middleware to the application pipeline, including security headers.
    /// </summary>
    /// <param name="app">The application builder</param>
    /// <returns>The application builder</returns>
    public static IApplicationBuilder UseIdmt(this IApplicationBuilder app)
    {
        var idmtOptions = app.ApplicationServices.GetRequiredService<IOptions<IdmtOptions>>().Value;

        // Security headers
        app.Use(async (context, next) =>
        {
            context.Response.Headers.XContentTypeOptions = "nosniff";
            context.Response.Headers.XFrameOptions = "DENY";
            context.Response.Headers["Referrer-Policy"] = "strict-origin-when-cross-origin";
            context.Response.Headers["Permissions-Policy"] = "geolocation=(), microphone=(), camera=()";
            await next();
        });

        // Rate limiting must be added before authentication so rejected requests
        // never reach identity processing. Only registered when the feature is enabled.
        if (idmtOptions.RateLimiting.Enabled)
        {
            app.UseRateLimiter();
        }

        // Add multi-tenant middleware - must come before authentication
        app.UseMultiTenant();

        // Add authentication and authorization
        app.UseAuthentication();
        app.UseAuthorization();

        // Add current user middleware after authentication
        app.UseMiddleware<ValidateBearerTokenTenantMiddleware>();
        app.UseMiddleware<CurrentUserMiddleware>();

        // Verify that the user store supports email operations (required for Idmt.Plugin)
        VerifyUserStoreSupportsEmail(app);

        return app;
    }

    /// <summary>
    /// Maps the IDMT endpoints under the configured API prefix. In case of route or
    /// basepath strategy, it's up to the caller to pass an adequate endpoint route builder.
    /// For example, if using the route strategy, the caller should pass the
    /// endpoint route builder for the tenant, e.g. `/{__tenant__?}`.
    ///
    /// The API prefix (e.g. "/api/v1") is read from
    /// <see cref="ApplicationOptions.ApiPrefix"/> and defaults to "/api/v1".
    /// Set it to an empty string to restore the legacy unprefixed behavior.
    /// </summary>
    /// <param name="endpoints">The endpoint route builder</param>
    /// <returns>The endpoint route builder</returns>
    /// <remarks>
    /// <para><b>OpenAPI security scheme</b></para>
    /// <para>
    /// IDMT does not configure OpenAPI itself. To expose the Bearer token scheme in the
    /// OpenAPI document generated by the host application, register an
    /// <c>IOpenApiDocumentTransformer</c> before calling <c>app.MapOpenApi()</c>.
    /// See the XML documentation on <c>AddIdmt</c> in
    /// <see cref="ServiceCollectionExtensions"/> for a complete code example.
    /// </para>
    /// </remarks>
    public static IEndpointRouteBuilder MapIdmtEndpoints(this IEndpointRouteBuilder endpoints)
    {
        var options = endpoints.ServiceProvider.GetRequiredService<IOptions<IdmtOptions>>();
        var apiPrefix = options.Value.Application.ApiPrefix ?? string.Empty;

        // Wrap all endpoint groups under the versioned prefix.
        // When apiPrefix is "" the group is effectively a pass-through.
        var prefixed = endpoints.MapGroup(apiPrefix);

        prefixed.MapAuthEndpoints();
        prefixed.MapAuthManageEndpoints();
        prefixed.MapAdminEndpoints();
        prefixed.MapHealthChecks("/healthz").RequireAuthorization(IdmtAuthOptions.RequireSysUserPolicy);
        return endpoints;
    }

    /// <summary>
    /// Initializes the IDMT database schema according to the configured
    /// <see cref="DatabaseOptions.DatabaseInitialization"/> mode.
    ///
    /// Only <see cref="IdmtDbContext"/> is used here because it owns all table
    /// configurations. <see cref="IdmtTenantStoreDbContext"/> shares the same
    /// physical database and connection, so no separate initialization is needed for it.
    ///
    /// <list type="bullet">
    ///   <item><see cref="DatabaseInitializationMode.Migrate"/> — applies pending EF Core migrations.
    ///   Recommended for production. Requires migrations to have been generated and added to
    ///   the consuming project.</item>
    ///   <item><see cref="DatabaseInitializationMode.EnsureCreated"/> — creates the schema without
    ///   a migrations history table. Suitable for development, testing, and prototyping.
    ///   Not compatible with migrations.</item>
    ///   <item><see cref="DatabaseInitializationMode.None"/> — skips all automatic initialization.
    ///   The consumer is responsible for managing the schema externally.</item>
    /// </list>
    /// </summary>
    /// <param name="app">The application builder</param>
    /// <returns>A task that completes when database initialization is done</returns>
    public static async Task EnsureIdmtDatabaseAsync(this IApplicationBuilder app)
    {
        using var scope = app.ApplicationServices.CreateScope();
        var services = scope.ServiceProvider;

        var options = services.GetRequiredService<IOptions<IdmtOptions>>();
        var context = services.GetRequiredService<IdmtDbContext>();

        switch (options.Value.Database.DatabaseInitialization)
        {
            case DatabaseInitializationMode.Migrate:
                await context.Database.MigrateAsync();
                break;
            case DatabaseInitializationMode.EnsureCreated:
                await context.Database.EnsureCreatedAsync();
                break;
            case DatabaseInitializationMode.None:
                break;
        }

        // NOTE: IdmtTenantStoreDbContext shares the same database/connection.
        // No separate initialization needed — it accesses tables created above.
    }

    /// <summary>
    /// Seeds initial data for multi-tenant setup
    /// </summary>
    /// <param name="app">The application builder</param>
    /// <param name="seedAction">Optional custom seed action</param>
    /// <returns>The application builder</returns>
    public static async Task<IApplicationBuilder> SeedIdmtDataAsync(this IApplicationBuilder app, SeedDataAsync? seedAction = null)
    {
        using var scope = app.ApplicationServices.CreateScope();
        var services = scope.ServiceProvider;
        // Run default seeding
        await SeedDefaultDataAsync(services);

        // Run custom seeding if provided
        if (seedAction != null)
        {
            await seedAction(services);
        }

        return app;
    }

    private static async Task SeedDefaultDataAsync(IServiceProvider services)
    {
        // Phase 1 / Step 9: bootstrap the default tenant directly via the tenant store + role
        // seeding rather than the admin CreateTenant handler. The handler now requires an
        // authenticated invoker (HS-4 / V2-CRIT-2 fail-closed) so it cannot run during app
        // startup where no HTTP context (and therefore no current user) exists.
        var options = services.GetRequiredService<IOptions<IdmtOptions>>();
        var tenantStore = services.GetRequiredService<Finbuckle.MultiTenant.Abstractions.IMultiTenantStore<IdmtTenantInfo>>();
        var defaultIdentifier = MultiTenantOptions.DefaultTenantIdentifier;

        var existing = await tenantStore.GetByIdentifierAsync(defaultIdentifier);
        IdmtTenantInfo defaultTenant;
        if (existing is null)
        {
            defaultTenant = new IdmtTenantInfo(defaultIdentifier, options.Value.MultiTenant.DefaultTenantName);
            if (!await tenantStore.AddAsync(defaultTenant))
            {
                throw new InvalidOperationException(
                    $"Failed to seed default tenant '{defaultIdentifier}'.");
            }
        }
        else if (!existing.IsActive)
        {
            defaultTenant = existing with { IsActive = true };
            if (!await tenantStore.UpdateAsync(defaultTenant))
            {
                throw new InvalidOperationException(
                    $"Failed to reactivate default tenant '{defaultIdentifier}'.");
            }
        }
        else
        {
            defaultTenant = existing;
        }

        // Seed default roles inside the tenant scope.
        var tenantOps = services.GetRequiredService<Idmt.Plugin.Services.ITenantOperationService>();
        var roles = IdmtDefaultRoleTypes.DefaultRoles;
        if (options.Value.Identity.ExtraRoles.Length > 0)
        {
            roles = [.. roles, .. options.Value.Identity.ExtraRoles];
        }

        var seedResult = await tenantOps.ExecuteInTenantScopeAsync(defaultTenant.Identifier!, async provider =>
        {
            var roleManager = provider.GetRequiredService<RoleManager<IdmtRole>>();
            foreach (var role in roles)
            {
                if (!await roleManager.RoleExistsAsync(role))
                {
                    var createResult = await roleManager.CreateAsync(new IdmtRole(role));
                    if (!createResult.Succeeded)
                    {
                        return Errors.IdmtErrors.Tenant.RoleSeedFailed;
                    }
                }
            }
            return ErrorOr.Result.Success;
        }, requireActive: false);

        if (seedResult.IsError)
        {
            throw new InvalidOperationException(
                $"Failed to seed default tenant '{defaultIdentifier}' roles: {seedResult.FirstError.Description}");
        }
    }

    private static void VerifyUserStoreSupportsEmail(IApplicationBuilder app)
    {
        using var scope = app.ApplicationServices.CreateScope();
        var userStore = scope.ServiceProvider.GetService<IUserStore<IdmtUser>>();
        if (userStore is null)
        {
            throw new InvalidOperationException("No IUserStore<IdmtUser> is registered. Ensure Identity is configured before calling UseIdmt().");
        }
        if (userStore is not IUserEmailStore<IdmtUser>)
        {
            throw new NotSupportedException("Idmt.Plugin requires a user store that supports email (IUserEmailStore<IdmtUser>).");
        }
    }
}